version: '3'
services:

    mysql:
      image: mysql:8.1.0
      container_name: wagner
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: indicium
      ports:
        - '3306:3306'
      volumes:
        - ./mysql:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql